server:
  port: 8761

spring:
  application:
    name: discovery
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  instance:
    hostname: discovery
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
