spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: orders
          uri: http://localhost:8050
          predicates:
            - Path=/order/**
        - id: users
          uri: http://localhost:8090
          predicates:
            - Path=/auth/**
        - id: products
          uri: http://localhost:8070
          predicates:
            - Path=/product/**

server:
  port: 8222

management:
  tracing:
    sampling:
      probability: 1.0
